# Generated by Django 5.2.17 on 2026-09-22 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='用户名')),
                ('session_key', models.CharField(blank=True, default='', max_length=64, verbose_name='会话ID')),
                ('path', models.CharField(max_length=255, verbose_name='请求路径')),
                ('full_url', models.TextField(blank=True, default='', verbose_name='完整URL')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('status_code', models.PositiveIntegerField(default=0, verbose_name='响应状态码')),
                ('duration_ms', models.FloatField(default=0, verbose_name='耗时(毫秒)')),
                ('referer', models.TextField(blank=True, default='', verbose_name='来源页')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('browser', models.CharField(blank=True, default='', max_length=100, verbose_name='浏览器')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='操作系统')),
                ('view_func', models.CharField(blank=True, default='', max_length=200, verbose_name='视图函数')),
                ('view_args', models.TextField(blank=True, default='', verbose_name='视图位置参数')),
                ('view_kwargs', models.TextField(blank=True, default='', verbose_name='视图关键字参数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='访问时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '访问日志',
                'verbose_name_plural': '访问日志',
                'db_table': 'blog_access_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='blog_access_created_f8ea98_idx'), models.Index(fields=['ip_address'], name='blog_access_ip_addr_760b47_idx'), models.Index(fields=['path'], name='blog_access_path_7f3ede_idx')],
            },
        ),
    ]
