# Generated by Django 5.2.17 on 2026-09-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_accesslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendlyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='链接名称')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('icon', models.CharField(blank=True, default='🔗', max_length=10, verbose_name='图标(emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序(小的在前)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'db_table': 'blog_friendly_link',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
