# Generated by Django 5.2.17 on 2026-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_friendlylink'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图'),
        ),
        migrations.AddField(
            model_name='article',
            name='excerpt_field',
            field=models.TextField(blank=True, default='', verbose_name='手动摘要'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
    ]
