# Generated by Django 5.2.17 on 2026-09-22 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='公告内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否显示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网站公告',
                'verbose_name_plural': '网站公告',
                'db_table': 'blog_site_notice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='是否置顶'),
        ),
        migrations.AddField(
            model_name='article',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='访问密码'),
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='定时发布时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='rating_avg',
            field=models.FloatField(default=0, verbose_name='平均评分'),
        ),
        migrations.AddField(
            model_name='article',
            name='rating_count',
            field=models.PositiveIntegerField(default=0, verbose_name='评分人数'),
        ),
        migrations.AddField(
            model_name='article',
            name='series_order',
            field=models.PositiveIntegerField(default=0, verbose_name='系列中序号'),
        ),
        migrations.AddField(
            model_name='editlog',
            name='content_snapshot',
            field=models.TextField(blank=True, default='', verbose_name='修改前内容快照'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='系列标题')),
                ('description', models.TextField(blank=True, verbose_name='系列介绍')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='series/', verbose_name='系列封面')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章系列',
                'verbose_name_plural': '文章系列',
                'db_table': 'blog_series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.series', verbose_name='所属系列'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
                'db_table': 'blog_rating',
                'ordering': ['-created_at'],
                'unique_together': {('article', 'user')},
            },
        ),
    ]
