# Generated by Django 5.2.17 on 2026-09-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_sitenotice_article_is_pinned_article_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='📁', max_length=10, verbose_name='图标(emoji)'),
        ),
    ]
