# Generated by Django 5.2.17 on 2026-09-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at', '-id'], 'permissions': [('can_review_comment', '可以审核评论')], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-created_at'], name='idx_art_status_ct'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_pinned', '-created_at'], name='idx_art_pinned_ct'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', '-created_at'], name='idx_art_cat_ct'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='idx_art_title'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['kind', 'status', '-created_at'], name='idx_art_kind_st_ct'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', '-created_at'], name='idx_cmt_article_ct'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment', '-created_at'], name='idx_cmt_parent_ct'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='idx_cmt_user_ct'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('rating_avg__gte', 0)), name='ck_art_rating_avg_nn'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.CheckConstraint(condition=models.Q(('rating_count__gte', 0)), name='ck_art_rating_cnt_nn'),
        ),
    ]
