# Generated by Django 5.2.17 on 2026-09-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_options_article_idx_art_status_ct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='share_count',
            field=models.PositiveIntegerField(default=0, verbose_name='分享次数'),
        ),
    ]
