# Generated by Django 5.2.17 on 2026-09-22 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_article_share_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='徽章名')),
                ('description', models.TextField(blank=True, default='', verbose_name='徽章说明')),
                ('icon', models.CharField(blank=True, default='🏅', max_length=20, verbose_name='图标(emoji)')),
                ('condition_type', models.CharField(choices=[('articles', '发文数'), ('comments', '评论数'), ('likes', '获赞数'), ('views', '阅读数'), ('days', '注册天数')], max_length=15, verbose_name='条件类型')),
                ('condition_value', models.IntegerField(default=1, verbose_name='条件阈值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '徽章',
                'verbose_name_plural': '徽章',
                'db_table': 'blog_badge',
                'ordering': ['condition_type', 'condition_value'],
            },
        ),
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='短码')),
                ('original_url', models.URLField(max_length=500, verbose_name='原始链接')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='点击次数')),
            ],
            options={
                'verbose_name': '短链接',
                'verbose_name_plural': '短链接',
                'db_table': 'blog_short_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='dislike_count',
            field=models.PositiveIntegerField(default=0, verbose_name='踩数'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/', verbose_name='评论图片'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_folded',
            field=models.BooleanField(default=False, verbose_name='是否折叠'),
        ),
        migrations.AddField(
            model_name='comment',
            name='reported',
            field=models.BooleanField(default=False, verbose_name='已举报'),
        ),
        migrations.AddField(
            model_name='user',
            name='amoled_dark',
            field=models.BooleanField(default=False, verbose_name='纯黑暗黑'),
        ),
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='user_bg/', verbose_name='个人主页背景'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_theme_color',
            field=models.CharField(blank=True, default='#a855f7', max_length=7, verbose_name='自定义主题色HEX'),
        ),
        migrations.AddField(
            model_name='user',
            name='effects_enabled',
            field=models.BooleanField(default=True, verbose_name='动效开关'),
        ),
        migrations.AddField(
            model_name='user',
            name='eye_protection',
            field=models.BooleanField(default=False, verbose_name='护眼模式'),
        ),
        migrations.AddField(
            model_name='user',
            name='font_family',
            field=models.CharField(choices=[('sans', '无衬线'), ('serif', '衬线'), ('mono', '等宽')], default='sans', max_length=10, verbose_name='字体'),
        ),
        migrations.AddField(
            model_name='user',
            name='font_size',
            field=models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大'), ('xlarge', '超大')], default='medium', max_length=10, verbose_name='字号'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True, verbose_name='最近活跃'),
        ),
        migrations.AddField(
            model_name='user',
            name='line_height',
            field=models.CharField(choices=[('tight', '紧凑'), ('normal', '正常'), ('relaxed', '宽松')], default='normal', max_length=10, verbose_name='行高'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='个性签名'),
        ),
        migrations.AddField(
            model_name='user',
            name='sound_enabled',
            field=models.BooleanField(default=False, verbose_name='音效开关'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme_color',
            field=models.CharField(choices=[('purple_pink', '紫粉'), ('blue_green', '蓝绿'), ('orange_yellow', '橙黄'), ('custom', '自定义')], default='purple_pink', max_length=20, verbose_name='主题色'),
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='举报原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='举报时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.comment', verbose_name='被举报评论')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reports', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'verbose_name': '评论举报',
                'verbose_name_plural': '评论举报',
                'db_table': 'blog_comment_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='收藏夹名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_folders', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '收藏夹',
                'verbose_name_plural': '收藏夹',
                'db_table': 'blog_favorite_folder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='favorite',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorites', to='blog.favoritefolder', verbose_name='收藏夹'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reply', '回复'), ('mention', '提及'), ('like', '点赞'), ('article', '文章'), ('system', '系统')], default='system', max_length=10, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='正文')),
                ('related_url', models.CharField(blank=True, default='', max_length=500, verbose_name='跳转链接')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'blog_notification',
                'ordering': ['-is_read', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='idx_notif_user_read')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='获得时间')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='blog.badge', verbose_name='徽章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户徽章',
                'verbose_name_plural': '用户徽章',
                'db_table': 'blog_user_badge',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
