# Generated by Django 5.2.17 on 2026-09-22 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_search_fulltext_seed_badges'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(max_length=30, verbose_name='导出类型')),
                ('format', models.CharField(default='json', max_length=10, verbose_name='格式')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='文件路径')),
                ('item_count', models.PositiveIntegerField(default=0, verbose_name='导出条数')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_export_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='变动积分')),
                ('reason', models.CharField(max_length=100, verbose_name='原因')),
                ('balance_after', models.PositiveIntegerField(verbose_name='变动后余额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_point_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='主题名称')),
                ('primary_color', models.CharField(default='#a06cd5', max_length=7, verbose_name='主色')),
                ('accent_color', models.CharField(default='#ff8fb1', max_length=7, verbose_name='强调色')),
                ('bg_color', models.CharField(default='#f4f2fb', max_length=7, verbose_name='背景色')),
                ('text_color', models.CharField(default='#2b2340', max_length=7, verbose_name='文字色')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否当前使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_presets', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_theme_preset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='密钥名称')),
                ('key_hash', models.CharField(max_length=128, unique=True, verbose_name='密钥哈希')),
                ('key_prefix', models.CharField(max_length=8, verbose_name='密钥前缀')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最后使用时间')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_api_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名称')),
                ('device_type', models.CharField(max_length=20, verbose_name='设备类型')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='操作系统')),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='浏览器')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('last_active_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前设备')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_device',
                'ordering': ['-last_active_at'],
            },
        ),
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight_text', models.TextField(blank=True, verbose_name='划线内容')),
                ('note_text', models.TextField(verbose_name='笔记内容')),
                ('color', models.CharField(default='#fff3cd', max_length=7, verbose_name='高亮颜色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='blog.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_note',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='总积分')),
                ('current_points', models.PositiveIntegerField(default=0, verbose_name='当前积分')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='等级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_point',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='个人简介')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='所在地')),
                ('website', models.URLField(blank=True, verbose_name='个人网站')),
                ('twitter', models.CharField(blank=True, max_length=100, verbose_name='Twitter')),
                ('github', models.CharField(blank=True, max_length=100, verbose_name='GitHub')),
                ('weibo', models.CharField(blank=True, max_length=100, verbose_name='微博')),
                ('bilibili', models.CharField(blank=True, max_length=100, verbose_name='B站')),
                ('avatar_bg', models.CharField(default='#a06cd5', max_length=7, verbose_name='头像背景色')),
                ('signature', models.CharField(blank=True, max_length=200, verbose_name='个性签名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ext', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(max_length=50, verbose_name='组件类型')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='位置')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('config', models.JSONField(default=dict, verbose_name='配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_widget',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='回调URL')),
                ('events', models.CharField(max_length=500, verbose_name='监听事件（逗号分隔）')),
                ('secret', models.CharField(max_length=100, verbose_name='签名密钥')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='最后触发时间')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='失败次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_webhook',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='笔记')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='blog.article', verbose_name='文章')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.favoritefolder', verbose_name='文件夹')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_article_bookmark',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ArticleHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题快照')),
                ('content', models.TextField(verbose_name='内容快照')),
                ('excerpt', models.TextField(blank=True, verbose_name='摘要快照')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本号')),
                ('change_summary', models.CharField(blank=True, max_length=300, verbose_name='修改说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_versions', to='blog.article', verbose_name='文章')),
                ('editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='编辑者')),
            ],
            options={
                'db_table': 'blog_article_history',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['article', '-version'], name='blog_articl_article_761be5_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20, verbose_name='平台')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='blog.article', verbose_name='文章')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_article_share',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', 'platform'], name='blog_articl_article_21a03c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CategoryFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.category', verbose_name='分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_follows', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_category_follow',
                'unique_together': {('user', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', '👍'), ('love', '❤️'), ('laugh', '😂'), ('wow', '😮'), ('sad', '😢'), ('fire', '🔥')], max_length=10, verbose_name='反应类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='blog.comment', verbose_name='评论')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_comment_reaction',
                'unique_together': {('user', 'comment', 'reaction_type')},
            },
        ),
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20, verbose_name='内容类型')),
                ('content_id', models.PositiveIntegerField(verbose_name='内容ID')),
                ('reason', models.CharField(choices=[('spam', '垃圾广告'), ('inappropriate', '不当内容'), ('copyright', '版权侵犯'), ('harassment', '骚扰'), ('other', '其他')], max_length=20, verbose_name='举报原因')),
                ('detail', models.TextField(blank=True, max_length=500, verbose_name='详细说明')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('resolved', '已处理'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='处理状态')),
                ('admin_note', models.TextField(blank=True, verbose_name='管理员备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
            ],
            options={
                'db_table': 'blog_content_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='blog_conten_status_e01a2b_idx'), models.Index(fields=['content_type', 'content_id'], name='blog_conten_content_e7f8ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP')),
                ('user_agent', models.CharField(max_length=500, verbose_name='User-Agent')),
                ('device_type', models.CharField(default='desktop', max_length=20, verbose_name='设备类型')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='地理位置')),
                ('success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_login_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='blog_login__user_id_610486_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('later', '稍后读'), ('reading', '在读'), ('read', '已读')], default='later', max_length=20, verbose_name='状态')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='优先级')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='读完时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_reading_lists', to='blog.article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_lists', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_reading_list',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField(verbose_name='计划发布时间')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否已发布')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='实际发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled', to='blog.article', verbose_name='文章')),
            ],
            options={
                'db_table': 'blog_scheduled_post',
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['is_published', 'scheduled_at'], name='blog_schedu_is_publ_f4d305_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='搜索词')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='结果数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_search_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query'], name='blog_search_query_5dff97_idx'), models.Index(fields=['user', '-created_at'], name='blog_search_user_id_f2f4a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TagFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.tag', verbose_name='标签')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_follows', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_tag_follow',
                'unique_together': {('user', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_key', models.CharField(max_length=50, verbose_name='成就标识')),
                ('title', models.CharField(max_length=100, verbose_name='成就名称')),
                ('description', models.CharField(max_length=300, verbose_name='成就描述')),
                ('icon', models.CharField(default='🏆', max_length=20, verbose_name='图标')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解锁时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_achievement',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement_key')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=30, verbose_name='行为类型')),
                ('target_type', models.CharField(blank=True, max_length=30, verbose_name='目标类型')),
                ('target_id', models.PositiveIntegerField(null=True, verbose_name='目标ID')),
                ('detail', models.CharField(blank=True, max_length=200, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'blog_user_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='blog_user_a_user_id_360de7_idx'), models.Index(fields=['action_type'], name='blog_user_a_action__4918cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_set', to=settings.AUTH_USER_MODEL, verbose_name='被屏蔽者')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking_set', to=settings.AUTH_USER_MODEL, verbose_name='屏蔽者')),
            ],
            options={
                'db_table': 'blog_user_block',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='关注时间')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to=settings.AUTH_USER_MODEL, verbose_name='关注者')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to=settings.AUTH_USER_MODEL, verbose_name='被关注者')),
            ],
            options={
                'db_table': 'blog_user_follow',
                'ordering': ['-created_at'],
                'unique_together': {('follower', 'following')},
            },
        ),
        migrations.CreateModel(
            name='UserMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('muted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_set', to=settings.AUTH_USER_MODEL, verbose_name='被静音者')),
                ('muter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muting_set', to=settings.AUTH_USER_MODEL, verbose_name='静音者')),
            ],
            options={
                'db_table': 'blog_user_mute',
                'unique_together': {('muter', 'muted')},
            },
        ),
    ]
