# Generated by Django 5.2.17 on 2026-09-24 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_round6_1000features'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已软删除'),
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已软删除'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布')], default='published', max_length=10, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator_name', models.CharField(blank=True, default='', max_length=150, verbose_name='审核人姓名')),
                ('action', models.CharField(choices=[('submit', '提交审核'), ('approve', '审核通过'), ('reject', '审核驳回'), ('soft_delete', '删除（隐藏）'), ('restore', '恢复'), ('hard_delete', '彻底删除')], max_length=15, verbose_name='审核动作')),
                ('target_type', models.CharField(default='article', max_length=10, verbose_name='对象类型')),
                ('target_title', models.CharField(blank=True, default='', max_length=200, verbose_name='对象标题快照')),
                ('reason', models.TextField(blank=True, default='', verbose_name='审核理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='blog.article', verbose_name='所属文章')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to='blog.comment', verbose_name='关联评论')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_logs', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
            options={
                'verbose_name': '审核日志',
                'verbose_name_plural': '审核日志',
                'db_table': 'blog_moderation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='idx_modlog_ct'), models.Index(fields=['article', '-created_at'], name='idx_modlog_art_ct'), models.Index(fields=['action'], name='idx_modlog_action')],
            },
        ),
    ]
