# Generated by Django 5.2.17 on 2026-09-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_deleted_at_article_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='萌语博客', help_text='显示在左上角 Logo、版权与浏览器标题后缀', max_length=60, verbose_name='网站名称')),
                ('logo_emoji', models.CharField(default='🌸', help_text='网站名称前的 Emoji，例如 🌸 / 🐱 / 🌟', max_length=8, verbose_name='Logo 表情')),
                ('tagline', models.CharField(default='一个粉紫蓝萌系的二次元小站，记录技术与生活的碎碎念喵~', max_length=120, verbose_name='网站副标题 / 一句话介绍')),
                ('description', models.TextField(default='萌语博客 · 一个粉紫蓝萌系的二次元小站，记录技术与生活的碎碎念喵~', verbose_name='网站描述（SEO meta description）')),
                ('keywords', models.CharField(default='博客,技术,二次元', max_length=200, verbose_name='网站关键词（SEO meta keywords，英文逗号分隔）')),
                ('footer_about', models.TextField(default='这里是萌语博客，记录技术笔记、生活随笔与各种小确幸。愿你在这里收获一点点温暖与灵感喵~ (◕ᴗ◕✿)', verbose_name='页脚「关于小站」文案')),
                ('footer_icp', models.CharField(blank=True, default='', max_length=80, verbose_name='备案号（选填，如 浙ICP备xxxxxxxx号）')),
                ('copyright_holder', models.CharField(blank=True, default='', max_length=60, verbose_name='版权归属名称（留空则用网站名称）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
                'db_table': 'blog_site_info',
            },
        ),
    ]
