# Generated by Django 5.2.17 on 2026-09-25 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_article_review', models.BooleanField(default=True, help_text='关闭后普通作者提交即发布；管理员发文始终可直接发布', verbose_name='普通作者新文章需审核')),
                ('require_comment_review', models.BooleanField(default=False, help_text='开启后新评论先待审核，通过后才公开', verbose_name='新评论需审核')),
                ('comment_recall_minutes', models.PositiveIntegerField(default=10, help_text='超过该时长不可自行撤回', verbose_name='评论可撤回时长（分钟）')),
                ('max_pinned', models.PositiveIntegerField(default=3, verbose_name='置顶文章数量上限')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '审核全局设置',
                'verbose_name_plural': '审核全局设置',
                'db_table': 'blog_moderation_settings',
            },
        ),
        migrations.CreateModel(
            name='PromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pin', '置顶'), ('feature', '精华'), ('hot', '热门')], max_length=10, verbose_name='申请类型')),
                ('reason', models.TextField(blank=True, default='', verbose_name='申请理由')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=10, verbose_name='状态')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
            ],
            options={
                'verbose_name': '推广申请',
                'verbose_name_plural': '推广申请',
                'db_table': 'blog_promotion_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='是否精华'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('submit', '提交审核'), ('approve', '审核通过'), ('reject', '审核驳回'), ('soft_delete', '删除（隐藏）'), ('restore', '恢复'), ('hard_delete', '彻底删除'), ('pin', '置顶'), ('unpin', '取消置顶'), ('feature', '加精华'), ('unfeature', '取消精华'), ('hot', '设热门'), ('unhot', '取消热门')], max_length=15, verbose_name='审核动作'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_featured', '-created_at'], name='idx_art_feat_ct'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['is_hot', '-created_at'], name='idx_art_hot_ct'),
        ),
        migrations.AddField(
            model_name='promotionrequest',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='promotionrequest',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='blog.article', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='promotionrequest',
            name='handled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddIndex(
            model_name='promotionrequest',
            index=models.Index(fields=['status', '-created_at'], name='idx_promo_status_ct'),
        ),
        migrations.AddIndex(
            model_name='promotionrequest',
            index=models.Index(fields=['kind', 'status'], name='idx_promo_kind_status'),
        ),
    ]
