"""
第5轮功能框架 · 路由（已精简）

历史背景：旧版 ``urls_autogenerated_11606.py`` 自动注册了 11,606 个“原子功能”
路由，但其视图全部为仅回显元数据的占位 stub，无任何真实业务逻辑，却显著拖慢
URL 解析与启动速度。这些 stub 已整体归档至 ``docs/archive/round5_stubs/``。

本模块现在只保留**真实可用**的“功能开关（feature flag）管理”端点：
- GET  /api/round5/features/                 列出所有已注册功能及开关状态
- POST /api/round5/features/<feature_id>/toggle/  切换功能开关（仅管理员）

后续若要新增真实功能，请在业务模块中用 ``@register_feature`` 注册，并在此显式
添加对应路由，禁止再批量生成无实现的占位路由。
"""
from django.urls import path
from django.views.decorators.http import require_GET, require_POST

from . import feature_list_view, feature_toggle_view

app_name = 'round5_features'

urlpatterns = [
    # 功能注册表（GET，返回所有真实注册功能及其启用状态）
    path('features/', require_GET(feature_list_view), name='feature_list'),
    # 功能开关切换（POST，仅 staff；请求体可传 {"enabled": true/false}）
    path('features/<str:feature_id>/toggle/',
         require_POST(feature_toggle_view), name='feature_toggle'),
]
