# -*- coding: utf-8 -*-

"""ACGBlog 视图包（blog.views）。

原 5700 余行的单文件 views.py 已按功能域拆分为 15 个子模块，
本 __init__ 统一 re-export 全部视图与公共工具，保持 ``blog.views.xxx``、
``from blog.views import xxx`` 与 urls.py 的引用完全兼容。

子模块一览：
- common：通用工具（净化/响应/分页/缓存/QuerySet）
- auth：登录注册登出
- articles：文章核心
- catalog：分类/标签/归档/侧边栏
- comments：评论
- users：用户资料/偏好/徽章/通知/收藏夹
- series：系列
- interactions：点赞/收藏/评分/热门/导出/短链
- search：搜索与补全
- api：DRF 接口
- seo：sitemap/RSS/robots/JSON-LD
- errors：404/500/403
- console：运营看板/站点设置/文案总表
- moderation：内容审核与推广审批
- features：Round5 功能开关
"""

from .api import (_Pagination, ArticleListCreateView, ArticleDetailView, _CsrfExemptSessionAuthentication,
                  ImageUploadView, CategoryListCreateView, CategoryDetailView, TagListCreateView, TagDetailView,
                  _AnonRateThrottle, ArticleV2ViewSet)
from .articles import (warm_public_cache, _get_related_articles, index, article_detail, _parse_form, article_new,
                       article_edit, article_delete, random_article)
from .auth import (login_view, register_view, logout_view)
from .catalog import (_build_sidebar, _sidebar, _tag_cloud_cached, _archive_cached, categories, category_detail, tags,
                      tag_detail, archive)
from .comments import (_build_comment_tree, comment_create, like_comment, COMMENT_IMAGE_MAX_BYTES,
                       COMMENT_IMAGE_ALLOWED_FORMATS, COMMENT_WITHDRAW_MINUTES, api_comment_image_upload,
                       api_comment_report, api_comment_delete)
from .common import (ARTICLE_TITLE_MAX_LENGTH, COMMENT_MAX_LENGTH, INTRODUCTION_MAX_LENGTH, NICKNAME_MAX_LENGTH,
                     SEARCH_Q_MAX_LENGTH, DEFAULT_PAGE_SIZE, HOT_ARTICLES_LIMIT, RELATED_ARTICLES_LIMIT,
                     TAG_CLOUD_LIMIT, READING_WORDS_PER_MINUTE, EXCERPT_DEFAULT_LENGTH, AVATAR_MAX_BYTES,
                     COVER_IMAGE_MAX_BYTES, SCHEDULED_CHECK_INTERVAL, ONLINE_WINDOW_MINUTES, ALLOWED_TAGS,
                     ALLOWED_ATTRIBUTES, ALLOWED_PROTOCOLS, COMMENT_ALLOWED_TAGS, COMMENT_ALLOWED_ATTRIBUTES,
                     COMMENT_ALLOWED_PROTOCOLS, sanitize_html, sanitize_comment, _safe_jsonld, _base_qs,
                     _filter_articles, SIDEBAR_CACHE_KEY, SIDEBAR_CACHE_TIMEOUT, FOOTER_STATS_KEY, HOT_ARTICLES_KEY,
                     TAG_CLOUD_KEY, ARCHIVE_KEY, VIEW_BUFFER_KEY, _optimized_list_qs, _qs_union, _iter_large_queryset,
                     _bulk_update_view_counts, _cache_get_or_set, _api_cache_page, _safe_paginate, _paginate_cached,
                     _clean_page_size, _clamp_page_number, _validate_page_jump, _seo_pagination_context,
                     _build_base_context, _eliminate_redundant_queries, _conditional_related, _lazy_context_provider,
                     _cached_context, _flatten_context, _default_context, _safe_context_value, _serialize_context,
                     _json_ok, _stream_text, _file_download, _redirect_302, _redirect_permanent, _not_modified,
                     _bad_request, _forbidden, _not_found, _paginate_qs)
from .console import (api_site_messages, server_status, API_ENDPOINTS, api_docs, staff_console, site_settings_page,
                      live2d_models_page,
                      MSG_DOMAIN_TITLES, _WIRED_CACHE, _RUNTIME_RECOMPUTING, _schedule_runtime_recompute,
                      _wired_message_keys, PAGE_ONLY_MSG_KEYS, site_messages_page, api_refresh_assets, dev_sync_state,
                      debug_cache_dump)
from .errors import (custom_404, custom_500, custom_403)
from .features import (Round5FeatureRegistry, round5_feature_list, round5_feature_toggle)
from .interactions import (_hot_articles_cached, _hot_articles_for_range, api_hot_articles, _site_stats_cached,
                           _article_detail_cached, like_article, toggle_favorite, rate_article, share_article,
                           SHORT_LINK_CODE_LEN, api_article_dislike, api_article_export_md, api_article_export_pdf,
                           api_article_qrcode, api_short_link, short_link_redirect)
from .moderation import (_moderation_backup, _article_snapshot, _comment_snapshot, moderation_queue, moderate_article,
                         moderate_report, _plain_snippet, restore_article, hard_delete_article, restore_comment,
                         hard_delete_comment, _PROMO_FIELD, _PROMO_LABEL, _promo_execute, _promo_block_state,
                         api_article_promotion_request, api_article_promotion_status, api_article_toggle_promotion,
                         moderate_promotion, moderation_settings_save)
from .search import (_search_results_cached, search, search_suggest, SEARCH_HOT_KEY, SEARCH_HOT_TTL, api_search_hot,
                     _record_search_keyword, _pinyin_keywords, _enhanced_search_suggest)
from .seo import (_build_website_jsonld, sitemap, rss_feed, robots_txt)
from .series import (series_list, series_detail, series_create)
from .users import (_user_profile_cached, _build_badge_panel, _BADGE_UNITS, _BADGE_HOW_TO, user_profile, user_settings,
                    my_articles, ONLINE_WINDOW, default_preferences, _preferences_dict, api_user_preferences,
                    api_favorite_folder_list, api_favorite_folder_detail, api_notification_list, api_notification_read,
                    api_notification_read_all, api_notification_unread_count, check_and_award_badges, api_user_badges,
                    api_online_users, notifications_page, my_favorites, my_liked, my_comments, reading_history_page)

__all__ = [
    'ARTICLE_TITLE_MAX_LENGTH',
    'COMMENT_MAX_LENGTH',
    'INTRODUCTION_MAX_LENGTH',
    'NICKNAME_MAX_LENGTH',
    'SEARCH_Q_MAX_LENGTH',
    'DEFAULT_PAGE_SIZE',
    'HOT_ARTICLES_LIMIT',
    'RELATED_ARTICLES_LIMIT',
    'TAG_CLOUD_LIMIT',
    'READING_WORDS_PER_MINUTE',
    'EXCERPT_DEFAULT_LENGTH',
    'AVATAR_MAX_BYTES',
    'COVER_IMAGE_MAX_BYTES',
    'SCHEDULED_CHECK_INTERVAL',
    'ONLINE_WINDOW_MINUTES',
    'ALLOWED_TAGS',
    'ALLOWED_ATTRIBUTES',
    'ALLOWED_PROTOCOLS',
    'COMMENT_ALLOWED_TAGS',
    'COMMENT_ALLOWED_ATTRIBUTES',
    'COMMENT_ALLOWED_PROTOCOLS',
    'sanitize_html',
    'sanitize_comment',
    '_safe_jsonld',
    '_base_qs',
    '_filter_articles',
    'SIDEBAR_CACHE_KEY',
    'SIDEBAR_CACHE_TIMEOUT',
    'FOOTER_STATS_KEY',
    'HOT_ARTICLES_KEY',
    'TAG_CLOUD_KEY',
    'ARCHIVE_KEY',
    'VIEW_BUFFER_KEY',
    '_optimized_list_qs',
    '_qs_union',
    '_iter_large_queryset',
    '_bulk_update_view_counts',
    '_cache_get_or_set',
    '_api_cache_page',
    '_safe_paginate',
    '_paginate_cached',
    '_clean_page_size',
    '_clamp_page_number',
    '_validate_page_jump',
    '_seo_pagination_context',
    '_build_base_context',
    '_eliminate_redundant_queries',
    '_conditional_related',
    '_lazy_context_provider',
    '_cached_context',
    '_flatten_context',
    '_default_context',
    '_safe_context_value',
    '_serialize_context',
    '_json_ok',
    '_stream_text',
    '_file_download',
    '_redirect_302',
    '_redirect_permanent',
    '_not_modified',
    '_bad_request',
    '_forbidden',
    '_not_found',
    '_paginate_qs',
    'Round5FeatureRegistry',
    'round5_feature_list',
    'round5_feature_toggle',
    '_build_sidebar',
    '_sidebar',
    '_tag_cloud_cached',
    '_archive_cached',
    'categories',
    'category_detail',
    'tags',
    'tag_detail',
    'archive',
    'warm_public_cache',
    '_get_related_articles',
    'index',
    'article_detail',
    '_parse_form',
    'article_new',
    'article_edit',
    'article_delete',
    'random_article',
    '_build_comment_tree',
    'comment_create',
    'like_comment',
    'COMMENT_IMAGE_MAX_BYTES',
    'COMMENT_IMAGE_ALLOWED_FORMATS',
    'COMMENT_WITHDRAW_MINUTES',
    'api_comment_image_upload',
    'api_comment_report',
    'api_comment_delete',
    'login_view',
    'register_view',
    'logout_view',
    '_user_profile_cached',
    '_build_badge_panel',
    '_BADGE_UNITS',
    '_BADGE_HOW_TO',
    'user_profile',
    'user_settings',
    'my_articles',
    'ONLINE_WINDOW',
    'default_preferences',
    '_preferences_dict',
    'api_user_preferences',
    'api_favorite_folder_list',
    'api_favorite_folder_detail',
    'api_notification_list',
    'api_notification_read',
    'api_notification_read_all',
    'api_notification_unread_count',
    'check_and_award_badges',
    'api_user_badges',
    'api_online_users',
    'notifications_page',
    'my_favorites',
    'my_liked',
    'my_comments',
    'reading_history_page',
    'series_list',
    'series_detail',
    'series_create',
    '_hot_articles_cached',
    '_hot_articles_for_range',
    'api_hot_articles',
    '_site_stats_cached',
    '_article_detail_cached',
    'like_article',
    'toggle_favorite',
    'rate_article',
    'share_article',
    'SHORT_LINK_CODE_LEN',
    'api_article_dislike',
    'api_article_export_md',
    'api_article_export_pdf',
    'api_article_qrcode',
    'api_short_link',
    'short_link_redirect',
    '_search_results_cached',
    'search',
    'search_suggest',
    'SEARCH_HOT_KEY',
    'SEARCH_HOT_TTL',
    'api_search_hot',
    '_record_search_keyword',
    '_pinyin_keywords',
    '_enhanced_search_suggest',
    '_Pagination',
    'ArticleListCreateView',
    'ArticleDetailView',
    '_CsrfExemptSessionAuthentication',
    'ImageUploadView',
    'CategoryListCreateView',
    'CategoryDetailView',
    'TagListCreateView',
    'TagDetailView',
    '_AnonRateThrottle',
    'ArticleV2ViewSet',
    '_build_website_jsonld',
    'sitemap',
    'rss_feed',
    'robots_txt',
    'custom_404',
    'custom_500',
    'custom_403',
    'api_site_messages',
    'server_status',
    'API_ENDPOINTS',
    'api_docs',
    'staff_console',
    'site_settings_page',
    'live2d_models_page',
    'MSG_DOMAIN_TITLES',
    '_WIRED_CACHE',
    '_RUNTIME_RECOMPUTING',
    '_schedule_runtime_recompute',
    '_wired_message_keys',
    'PAGE_ONLY_MSG_KEYS',
    'site_messages_page',
    'api_refresh_assets',
    'dev_sync_state',
    'debug_cache_dump',
    '_moderation_backup',
    '_article_snapshot',
    '_comment_snapshot',
    'moderation_queue',
    'moderate_article',
    'moderate_report',
    '_plain_snippet',
    'restore_article',
    'hard_delete_article',
    'restore_comment',
    'hard_delete_comment',
    '_PROMO_FIELD',
    '_PROMO_LABEL',
    '_promo_execute',
    '_promo_block_state',
    'api_article_promotion_request',
    'api_article_promotion_status',
    'api_article_toggle_promotion',
    'moderate_promotion',
    'moderation_settings_save',
]
